"""empty message

Revision ID: 136ccdf8edc3
Revises: 511de5a230b2
Create Date: 2026-04-05 20:35:19.313609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136ccdf8edc3'
down_revision = '511de5a230b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('os_taget', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('agents',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('agent_token', sa.Text(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=True),
    sa.Column('agent_version', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.pid'], ),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('agent_token'),
    sa.UniqueConstraint('server_id')
    )
    op.create_table('jobs',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.pid'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.pid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('job_results',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.pid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_results')
    op.drop_table('jobs')
    op.drop_table('agents')
    op.drop_table('scripts')
    # ### end Alembic commands ###
