"""empty message

Revision ID: 511de5a230b2
Revises: d2a6b338c9b1
Create Date: 2026-04-04 23:01:27.758495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511de5a230b2'
down_revision = 'd2a6b338c9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('ip')

    # ### end Alembic commands ###
