"""Add resource columns to Agent

Revision ID: 831d6b6d4f18
Revises: 136ccdf8edc3
Create Date: 2026-04-07 11:30:21.161436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831d6b6d4f18'
down_revision = '136ccdf8edc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_usage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ram_usage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disk_usage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('disk_usage')
        batch_op.drop_column('ram_usage')
        batch_op.drop_column('cpu_usage')

    # ### end Alembic commands ###
