"""Add sudo fields to Script

Revision ID: d3cf9cfe812f
Revises: 831d6b6d4f18
Create Date: 2026-04-08 15:22:22.532930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cf9cfe812f'
down_revision = '831d6b6d4f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_sudo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sudo_password', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.drop_column('sudo_password')
        batch_op.drop_column('use_sudo')

    # ### end Alembic commands ###
